### ISSUE TITLE
Hạn chế sử dụng SuppressWarning("deprecation")

### ISSUE THREAD

**Issue by Banbeucmas** [letruongthinh/Mantle-#1]
Về Suppress Warning:
Không cần thiết lắm. Bukkit API nếu cần thì add thôi.
Event là điển hình

Đừng check #equal() với Enum: https://github.com/letruongthinh/Mantle-/blob/master/src/main/java/io/lethinh/github/mantle/event/FastCropsHarvestEvent.java#L34
https://github.com/letruongthinh/Mantle-/blob/master/src/main/java/io/lethinh/github/mantle/event/BedrockBreakEvent.java#L31

Sẽ an toàn hơn nếu check bằng toán tử

**Comment by n3sfan** [comment]
ok bệu :D

**Comment by n3sfan** [comment]
fix r bác bệu close nha :3
